-- 모든 테이블 삭제 (PURGE 통해 완벽삭제 요망) -- 
DROP TABLE MEMBER
DROP TABLE MEMBER1
DROP TABLE CLASSGROUP
DROP TABLE CLASS
DROP TABLE MEMBER2
DROP TABLE MEMBER3
DROP TABLE ITEM
DROP TABLE CLASSDETIL2
DROP TABLE CLASSDETIL
DROP TABLE CLASSESTIMATE
DROP TABLE RECORD
DROP TABLE RECORDISSUE
DROP TABLE TEST
DROP TABLE SANSWER
DROP TABLE BOARD
PURGE RECYCLEBIN

--각테이블 고유번호 시퀀스삭제--
DROP SEQUENCE sq_MEMBER1_idx
DROP SEQUENCE sq_MEMBER2_m2idx
DROP SEQUENCE sq_MEMBER3_m3idx
DROP SEQUENCE sq_CLASSGROUP_groupidx
DROP SEQUENCE sq_ITEM_itemidx
DROP SEQUENCE sq_CLASS_classidx
DROP SEQUENCE sq_CLASSDETIL2_weekidx
DROP SEQUENCE sq_CLASSDETIL_class2idx
DROP SEQUENCE sq_CLASSESTIMATE_estidx
DROP SEQUENCE sq_RECORD_recordidx
DROP SEQUENCE sq_RECORDISSUE_issueidx
DROP SEQUENCE sq_TEST_testidx
DROP SEQUENCE sq_SANSWER_sansweridx
DROP SEQUENCE sq_BOARD_boardidx
